### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gety9** [nickrigby/Magento-Stripe-Payments#1]
What kind of license does this project have?

Is it free to use?

**Comment by nickrigby** [comment]
Yup, it’s free

**Comment by gety9** [comment]
Could you add license saying it's free to use?

Cause seems like if there is no license specified than it's not free. 

References: 
https://github.com/github/choosealicense.com/issues/196

**Comment by nickrigby** [comment]
Yeah, of course

**Comment by gety9** [comment]
Thank you

**Comment by gety9** [comment]
@nickrigby 

Sorry to bother, but any update on that? Would really like to see free to use license notice.

**Comment by nickrigby** [comment]
Added! Apologies for the delay.

**Comment by gety9** [comment]
@nickrigby thank you!
